---
substitutions:
  name: "econet-hvac"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"

packages:
  econet: !include econet_base.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/econet_hvac.yaml@${github_ref}
  import_full_config: false

econet:
  dst_address: 0x380

climate:
  - platform: econet
    name: "HVAC"
    visual:
      min_temperature: "10"
      max_temperature: "32.2222"
      temperature_step: 1.0f
    current_temperature_datapoint: SPT_STAT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STATNFAN
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"

sensor:
  - platform: econet
    name: "HVAC Airhandler CFM"
    id: hvac_airhandler_cfm
    sensor_datapoint: F_ACTCFM
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC Airhandler RPM"
    id: hvac_airhandler_rpm
    sensor_datapoint: F_ACTRPM
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC Static Pressure"
    id: hvac_static_pressure
    sensor_datapoint: STATIC_P
    unit_of_measurement: "in"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC Register Air Temperature"
    id: hvac_register_air_temperature
    sensor_datapoint: TEMP_LAT
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC Return Air Temperature"
    id: hvac_return_air_temperature
    sensor_datapoint: TEMP_RAT
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Thermostat Current Humidity"
    id: thermostat_current_humidity
    sensor_datapoint: RELH7005
    unit_of_measurement: "%"
    accuracy_decimals: 1
    device_class: "humidity"
    state_class: "measurement"
  - platform: econet
    name: "HVAC Active Alerts"
    id: hvac_active_alerts
    sensor_datapoint: ALRMALRT
    request_mod: 1
    accuracy_decimals: 0
    icon: "mdi:alert"
    state_class: "measurement"
    entity_category: "diagnostic"

text_sensor:
  - platform: econet
    name: "HVAC Operating Mode"
    id: hvac_operating_mode
    sensor_datapoint: HVACMODE
  - platform: econet
    name: "HVAC Auto Mode"
    id: hvac_auto_mode
    sensor_datapoint: AUTOMODE
    
number:
  - platform: econet
    name: "HVAC Dehumidification Setting Control"
    id: hvac_dehumidification_setting_control
    number_datapoint: DHUMSETP
    min_value: 10
    max_value: 80
    step: 1
    mode: "slider"
    icon: "mdi:air-humidifier-off"

switch:
  - platform: econet
    name: "HVAC Dehumidification Enable State"
    id: hvac_dehumidification_enable_state
    switch_datapoint: DHUMENAB
    icon: "mdi:air-humidifier-off"

binary_sensor:
  - platform: econet
    name: "HVAC Electric Heat Relay 1"
    id: hvac_electric_heat_relay_1
    sensor_datapoint: HT1_RELY
    icon: "mdi:heating-coil"
    entity_category: "diagnostic"
    disabled_by_default: true
  - platform: econet
    name: "HVAC Electric Heat Relay 2"
    id: hvac_electric_heat_relay_2
    sensor_datapoint: HT2_RELY
    icon: "mdi:heating-coil"
    entity_category: "diagnostic"
    disabled_by_default: true
