---
substitutions:
  name: "econet-etwh"
  friendly_name: "Water Heater"
  device_description: "Rheem Electric Tank Water Heater"
  sensor_power_filters_lambda: return x;

packages:
  econet: !include econet_base.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/econet_electric_tank_water_heater.yaml@main
  import_full_config: false

econet:
  model: "Electric Tank"

climate:
  - platform: econet
    name: None
    visual:
      min_temperature: "43.3333"
      max_temperature: "60"
      temperature_step: 1.0f

sensor:
  - platform: econet
    name: "Lower Tank Temperature"
    sensor_datapoint: LOHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Upper Tank Temperature"
    sensor_datapoint: UPHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Power"
    sensor_datapoint: POWRWATT
    unit_of_measurement: "W"
    accuracy_decimals: 3
    device_class: "power"
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - lambda: ${sensor_power_filters_lambda}

text_sensor:
  - platform: econet
    name: "Heating Element State"
    sensor_datapoint: HEATCTRL
    icon: "mdi:heating-coil"
  - platform: econet
    name: "Mode"
    sensor_datapoint: WHTRMODE
    entity_category: "diagnostic"
