substitutions:
  name: "econet-hvac"
  device_description: "Econet HVAC"
  tx_pin: GPIO19
  rx_pin: GPIO22

esphome:
  name: ${name}
  comment: ${device_description}

preferences:
  flash_write_interval: "24h"

esp32:
  board: esp32dev
  framework: 
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:

logger:
  baud_rate: 0 # Make sure logging is not using the serial port
  level: INFO
  tx_buffer_size: 2000

external_components:
  # - source: github://stockmopar/esphome-econet
 - source: components

uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

econet:
  uart_id: uart_0
  model: "HVAC"

climate:
  - platform: econet
    name: "HVAC"

sensor:
  - platform: econet
    name: "HVAC Operating Mode"
    sensor_datapoint: HVACMODE
    unit_of_measurement: ""
    accuracy_decimals: 0
  - platform: econet
    name: "HVAC Thermostat Temperature"
    sensor_datapoint: SPT_STAT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
  - platform: econet
    name: "HVAC Cooling Setpoint"
    sensor_datapoint: COOLSETP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
  - platform: econet
    name: "HVAC Auto Mode"
    sensor_datapoint: AUTOMODE
    unit_of_measurement: ""
    accuracy_decimals: 0
