---
substitutions:
  name: "econet-tlwh"
  friendly_name: "Tankless Water Heater"
  device_description: "Rheem Tankless Water Heater"
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev
  external_components_source: github://stockmopar/esphome-econet@main
  logger_level: WARN

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  min_version: "2023.2.0"
  platform: $platform
  board: $board
  project:
    name: "stockmopar.econet"
    version: 0.2.3

dashboard_import:
  package_import_url: github://stockmopar/esphome-econet/econet_tankless_water_heater.yaml@main
  import_full_config: false

preferences:
  flash_write_interval: "24h"

wifi:
  ap:

captive_portal:

api:

ota:

logger:
  baud_rate: 0  # Make sure logging is not using the serial port
  level: ${logger_level}
  tx_buffer_size: 2000

external_components:
  - source: ${external_components_source}

uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

econet:
  uart_id: uart_0
  model: "Tankless"

climate:
  - platform: econet
    name: None
    visual:
      min_temperature: "43.3333"
      max_temperature: "60"
      temperature_step: 1.0f

sensor:
  - platform: econet
    name: "Temperature In"
    id: temp_in
    sensor_datapoint: TEMP__IN
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Temperature Out"
    id: temp_out
    sensor_datapoint: TEMP_OUT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "BTUs Used"
    sensor_datapoint: WTR_BTUS
    unit_of_measurement: "kbtu"
    accuracy_decimals: 3
    entity_category: "diagnostic"
    icon: "mdi:flash"
  - platform: econet
    name: "Water Used"
    sensor_datapoint: WTR_USED
    unit_of_measurement: "gal"
    accuracy_decimals: 1
    device_class: "water"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Flow Rate"
    id: flow_rate
    sensor_datapoint: FLOWRATE
    unit_of_measurement: "gpm"
    accuracy_decimals: 1
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      # Convert liters per minute to gpm
      - multiply: 0.264172
    icon: "mdi:water"
  - platform: econet
    name: "Ignition Cycles"
    sensor_datapoint: IGNCYCLS
    unit_of_measurement: ""
    accuracy_decimals: 0
    entity_category: "diagnostic"
    icon: "mdi:heating-coil"
  - platform: template
    name: "Instant BTUs"
    unit_of_measurement: "kbtu/hr"
    accuracy_decimals: 3
    state_class: "measurement"
    entity_category: "diagnostic"
    # yamllint disable rule:line-length
    lambda: |-
      return max((id(temp_out).state - id(temp_in).state) * id(flow_rate).state * 8.334 * 60 / 0.92 / 1000, 0.0);
    # yamllint enable rule:line-length
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 30s
    entity_category: "diagnostic"
