substitutions:
  name: econet
  device_description: "Communicate with Econet Netork"
  tx_pin: GPIO19
  rx_pin: GPIO22

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "stockmopar.econet"
    version: 0.0.1
  includes:
    - my_custom_component.h

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  level: DEBUG

api:

uart:
  id: uart0
  baud_rate: 38400
  tx_pin: 
    number: ${tx_pin}
  rx_pin:
    number: ${rx_pin}

custom_component:
- id: my_econet
  lambda: |-
    auto my_econet_component = new EconetRS485(id(uart0));
    return {my_econet_component};

sensor:
- platform: custom
  lambda: |-
    return {get_econet(my_econet)->flow_rate_sensor,
            get_econet(my_econet)->temp_out_sensor,
            get_econet(my_econet)->temp_in_sensor,
            get_econet(my_econet)->setpoint_temp_sensor,
            get_econet(my_econet)->water_used_sensor,
            get_econet(my_econet)->btus_used_sensor,
            get_econet(my_econet)->ign_cycle_counts_sensor,
            get_econet(my_econet)->instant_btus_sensor
            };
  sensors:
  - name: "Flow Rate"
    unit_of_measurement: gpm
    accuracy_decimals: 2
  - name: "Temperature Out"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Temperature In"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Set Point Temperature"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Water Used"
    unit_of_measurement: gal
    accuracy_decimals: 1
  - name: "BTUs Used"
    unit_of_measurement: kbtu
    accuracy_decimals: 3
  - name: "Ignition Cycles"
    accuracy_decimals: 0
  - name: "Instant BTUs"
    unit_of_measurement: kbtu/hr
    accuracy_decimals: 3

binary_sensor:
- platform: custom
  lambda: |-
    return {wh_enabled_binary_sensor(my_econet)
            };
  binary_sensors:
     name: "Water Heater Enabled (Sensor)"
     id: wh_enabled_sensor

switch:
- platform: custom
  lambda: |-
    return {wh_enabled_switch(my_econet)
            };
  switches:
     name: "Water Heater Enabled"
     id: wh_enabled_switch
