---
substitutions:
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev
  uart_id: uart_1  # Need to free up UART_0 for the logger to enable improv_serial

wifi:
  ap:

logger:
  baud_rate: 115200
  level: ${logger_level}
  tx_buffer_size: 512
  hardware_uart: UART0

improv_serial:
