---
substitutions:
  tx_pin: GPIO4
  rx_pin: GPIO5
  platform: esp8266
  board: d1_mini
  uart_id: uart_1

wifi:
  ap:

logger:
  baud_rate: 115200  # Make sure logging is not using the serial port
  level: ${logger_level}
  tx_buffer_size: 512
  hardware_uart: UART0

improv_serial:
